// Mock data for FitConnect Marketplace
import { Coach, Booking, Conversation, Message, Review, User } from './types';

// Avatar URLs using UI Faces placeholder service
const avatars = [
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
];

// Fitness images for gallery
const fitnessImages = [
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1581009146145-b5ef050c149a?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=400&fit=crop',
];

export const coaches: Coach[] = [
    {
        id: '1',
        name: 'Sarah Mitchell',
        avatar: avatars[2],
        gallery: [fitnessImages[0], fitnessImages[1], fitnessImages[2], fitnessImages[3]],
        bio: 'Former Division I athlete with 8+ years of personal training experience. I specialize in strength training and athletic performance, helping clients achieve their fitness goals through science-backed methods and personalized programming. My approach combines functional movement patterns with progressive overload principles.',
        tagline: 'Transform your body, elevate your performance',
        specialties: ['Strength Training', 'Athletic Performance', 'Weight Loss'],
        certifications: ['NASM-CPT', 'CSCS', 'USA Weightlifting L1'],
        location: 'New York, NY',
        languages: ['English', 'Spanish'],
        rating: 4.9,
        reviewCount: 127,
        sessionsCompleted: 842,
        responseTime: 'Usually within 1 hour',
        startingRate: 75,
        packages: [
            { id: 'p1', title: 'Power Session', duration: 30, price: 75, type: 'in-person', description: 'Focused 30-minute high-intensity session' },
            { id: 'p2', title: 'Full Training', duration: 60, price: 120, type: 'in-person', description: 'Complete 60-minute personalized workout' },
            { id: 'p3', title: 'Online Coaching', duration: 45, price: 65, type: 'online', description: 'Virtual session with real-time feedback' },
        ],
        availability: [
            { day: 'Monday', slots: ['7:00 AM', '9:00 AM', '2:00 PM', '5:00 PM'] },
            { day: 'Tuesday', slots: ['8:00 AM', '10:00 AM', '3:00 PM', '6:00 PM'] },
            { day: 'Wednesday', slots: ['7:00 AM', '9:00 AM', '2:00 PM'] },
            { day: 'Thursday', slots: ['8:00 AM', '10:00 AM', '4:00 PM', '6:00 PM'] },
            { day: 'Friday', slots: ['7:00 AM', '9:00 AM', '1:00 PM'] },
        ],
        verified: true,
    },
    {
        id: '2',
        name: 'Marcus Johnson',
        avatar: avatars[1],
        gallery: [fitnessImages[4], fitnessImages[5], fitnessImages[0], fitnessImages[2]],
        bio: 'Bodybuilding competitor and nutrition specialist with a passion for helping others build lean muscle and achieve their dream physique. I believe in sustainable approaches that combine proper training with nutrition optimization.',
        tagline: 'Build muscle, build confidence',
        specialties: ['Bodybuilding', 'Nutrition', 'Muscle Building'],
        certifications: ['ISSA-CPT', 'Precision Nutrition L1', 'ACE-CPT'],
        location: 'Los Angeles, CA',
        languages: ['English'],
        rating: 4.8,
        reviewCount: 89,
        sessionsCompleted: 623,
        responseTime: 'Usually within 2 hours',
        startingRate: 85,
        packages: [
            { id: 'p4', title: 'Hypertrophy Session', duration: 60, price: 85, type: 'in-person', description: 'Muscle-building focused training' },
            { id: 'p5', title: 'Competition Prep', duration: 90, price: 150, type: 'in-person', description: 'Intensive prep for competitions' },
            { id: 'p6', title: 'Nutrition Consult', duration: 45, price: 70, type: 'online', description: 'Personalized meal planning session' },
        ],
        availability: [
            { day: 'Monday', slots: ['6:00 AM', '8:00 AM', '4:00 PM'] },
            { day: 'Tuesday', slots: ['6:00 AM', '10:00 AM', '5:00 PM'] },
            { day: 'Wednesday', slots: ['6:00 AM', '8:00 AM', '4:00 PM'] },
            { day: 'Thursday', slots: ['6:00 AM', '10:00 AM', '5:00 PM'] },
            { day: 'Friday', slots: ['6:00 AM', '8:00 AM', '12:00 PM'] },
        ],
        verified: true,
    },
    {
        id: '3',
        name: 'Emma Chen',
        avatar: avatars[0],
        gallery: [fitnessImages[1], fitnessImages[3], fitnessImages[5], fitnessImages[4]],
        bio: 'Yoga instructor and wellness coach dedicated to helping you find balance in mind and body. With certifications in multiple yoga styles and mindfulness practices, I create personalized programs that reduce stress and increase flexibility.',
        tagline: 'Find your balance, find your strength',
        specialties: ['Yoga', 'Flexibility', 'Mindfulness'],
        certifications: ['RYT-500', 'ACE-GFI', 'Meditation Teacher'],
        location: 'San Francisco, CA',
        languages: ['English', 'Mandarin'],
        rating: 5.0,
        reviewCount: 156,
        sessionsCompleted: 1024,
        responseTime: 'Usually within 30 minutes',
        startingRate: 60,
        packages: [
            { id: 'p7', title: 'Flow Session', duration: 60, price: 60, type: 'online', description: 'Guided vinyasa flow practice' },
            { id: 'p8', title: 'Private Yoga', duration: 75, price: 95, type: 'in-person', description: 'One-on-one customized yoga session' },
            { id: 'p9', title: 'Meditation & Breath', duration: 30, price: 40, type: 'online', description: 'Guided meditation and breathwork' },
        ],
        availability: [
            { day: 'Monday', slots: ['6:00 AM', '9:00 AM', '6:00 PM'] },
            { day: 'Tuesday', slots: ['6:00 AM', '9:00 AM', '6:00 PM'] },
            { day: 'Wednesday', slots: ['6:00 AM', '9:00 AM', '6:00 PM'] },
            { day: 'Thursday', slots: ['6:00 AM', '9:00 AM', '6:00 PM'] },
            { day: 'Friday', slots: ['6:00 AM', '9:00 AM'] },
            { day: 'Saturday', slots: ['8:00 AM', '10:00 AM'] },
        ],
        verified: true,
    },
    {
        id: '4',
        name: 'James Rodriguez',
        avatar: avatars[3],
        gallery: [fitnessImages[2], fitnessImages[0], fitnessImages[4], fitnessImages[1]],
        bio: 'CrossFit Level 3 trainer and former professional soccer player. I bring the intensity and discipline of professional athletics to every session. Specializing in functional fitness and HIIT training that delivers real-world results.',
        tagline: 'Train like an athlete, perform like a champion',
        specialties: ['CrossFit', 'HIIT', 'Functional Fitness'],
        certifications: ['CrossFit L3', 'NASM-CES', 'TRX Certified'],
        location: 'Miami, FL',
        languages: ['English', 'Portuguese', 'Spanish'],
        rating: 4.7,
        reviewCount: 203,
        sessionsCompleted: 1456,
        responseTime: 'Usually within 3 hours',
        startingRate: 70,
        packages: [
            { id: 'p10', title: 'WOD Session', duration: 45, price: 70, type: 'in-person', description: 'Intense CrossFit workout of the day' },
            { id: 'p11', title: 'Athletic Training', duration: 60, price: 95, type: 'in-person', description: 'Sport-specific conditioning' },
            { id: 'p12', title: 'HIIT Express', duration: 30, price: 55, type: 'online', description: 'Quick high-intensity interval training' },
        ],
        availability: [
            { day: 'Monday', slots: ['5:00 AM', '7:00 AM', '5:00 PM', '7:00 PM'] },
            { day: 'Tuesday', slots: ['5:00 AM', '7:00 AM', '5:00 PM', '7:00 PM'] },
            { day: 'Wednesday', slots: ['5:00 AM', '7:00 AM', '5:00 PM'] },
            { day: 'Thursday', slots: ['5:00 AM', '7:00 AM', '5:00 PM', '7:00 PM'] },
            { day: 'Friday', slots: ['5:00 AM', '7:00 AM'] },
            { day: 'Saturday', slots: ['7:00 AM', '9:00 AM', '11:00 AM'] },
        ],
        verified: true,
    },
    {
        id: '5',
        name: 'Rachel Kim',
        avatar: avatars[4],
        gallery: [fitnessImages[5], fitnessImages[2], fitnessImages[1], fitnessImages[3]],
        bio: 'Pilates master trainer and rehabilitation specialist. I help clients recover from injuries, improve posture, and build core strength through precise, controlled movements. Perfect for those seeking low-impact but highly effective training.',
        tagline: 'Precision movement for lasting results',
        specialties: ['Pilates', 'Rehabilitation', 'Posture Correction'],
        certifications: ['BASI Pilates', 'NASM-CES', 'PMA-CPT'],
        location: 'Chicago, IL',
        languages: ['English', 'Korean'],
        rating: 4.9,
        reviewCount: 78,
        sessionsCompleted: 534,
        responseTime: 'Usually within 1 hour',
        startingRate: 80,
        packages: [
            { id: 'p13', title: 'Mat Pilates', duration: 45, price: 80, type: 'in-person', description: 'Classical mat Pilates session' },
            { id: 'p14', title: 'Reformer Session', duration: 60, price: 110, type: 'in-person', description: 'Pilates reformer training' },
            { id: 'p15', title: 'Posture Assessment', duration: 30, price: 50, type: 'online', description: 'Virtual posture analysis and correction plan' },
        ],
        availability: [
            { day: 'Monday', slots: ['8:00 AM', '10:00 AM', '2:00 PM', '4:00 PM'] },
            { day: 'Tuesday', slots: ['8:00 AM', '10:00 AM', '2:00 PM'] },
            { day: 'Wednesday', slots: ['8:00 AM', '10:00 AM', '2:00 PM', '4:00 PM'] },
            { day: 'Thursday', slots: ['8:00 AM', '10:00 AM', '2:00 PM'] },
            { day: 'Friday', slots: ['8:00 AM', '10:00 AM'] },
        ],
        verified: true,
    },
    {
        id: '6',
        name: 'David Thompson',
        avatar: avatars[5],
        gallery: [fitnessImages[3], fitnessImages[4], fitnessImages[0], fitnessImages[5]],
        bio: 'Kettlebell specialist and endurance coach with a focus on building functional strength and cardiovascular fitness. Former marathon runner who understands the importance of balanced training for peak performance.',
        tagline: 'Endurance meets strength',
        specialties: ['Kettlebell Training', 'Endurance', 'Running'],
        certifications: ['StrongFirst SFG', 'RRCA Running Coach', 'ACE-CPT'],
        location: 'Boston, MA',
        languages: ['English'],
        rating: 4.6,
        reviewCount: 64,
        sessionsCompleted: 412,
        responseTime: 'Usually within 4 hours',
        startingRate: 65,
        packages: [
            { id: 'p16', title: 'Kettlebell Basics', duration: 45, price: 65, type: 'in-person', description: 'Learn proper kettlebell technique' },
            { id: 'p17', title: 'Run Coaching', duration: 60, price: 80, type: 'in-person', description: 'Form analysis and training plan' },
            { id: 'p18', title: 'Endurance Plan', duration: 45, price: 55, type: 'online', description: 'Custom endurance programming' },
        ],
        availability: [
            { day: 'Monday', slots: ['6:00 AM', '4:00 PM', '6:00 PM'] },
            { day: 'Tuesday', slots: ['6:00 AM', '4:00 PM', '6:00 PM'] },
            { day: 'Wednesday', slots: ['6:00 AM', '4:00 PM'] },
            { day: 'Thursday', slots: ['6:00 AM', '4:00 PM', '6:00 PM'] },
            { day: 'Saturday', slots: ['7:00 AM', '9:00 AM'] },
            { day: 'Sunday', slots: ['8:00 AM', '10:00 AM'] },
        ],
        verified: false,
    },
];

export const currentUser: User = {
    id: 'user1',
    name: 'Alex Morgan',
    email: 'alex.morgan@email.com',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face',
    role: 'client',
};

export const bookings: Booking[] = [
    {
        id: 'b1',
        coachId: '1',
        coachName: 'Sarah Mitchell',
        coachAvatar: avatars[2],
        clientId: 'user1',
        clientName: 'Alex Morgan',
        packageId: 'p2',
        packageTitle: 'Full Training',
        datetime: '2026-01-20T09:00:00',
        status: 'upcoming',
        amount: 120,
        platformFee: 12,
        payoutAmount: 108,
    },
    {
        id: 'b2',
        coachId: '3',
        coachName: 'Emma Chen',
        coachAvatar: avatars[0],
        clientId: 'user1',
        clientName: 'Alex Morgan',
        packageId: 'p7',
        packageTitle: 'Flow Session',
        datetime: '2026-01-22T06:00:00',
        status: 'upcoming',
        amount: 60,
        platformFee: 6,
        payoutAmount: 54,
    },
    {
        id: 'b3',
        coachId: '2',
        coachName: 'Marcus Johnson',
        coachAvatar: avatars[1],
        clientId: 'user1',
        clientName: 'Alex Morgan',
        packageId: 'p4',
        packageTitle: 'Hypertrophy Session',
        datetime: '2026-01-10T10:00:00',
        status: 'completed',
        amount: 85,
        platformFee: 8.5,
        payoutAmount: 76.5,
    },
    {
        id: 'b4',
        coachId: '1',
        coachName: 'Sarah Mitchell',
        coachAvatar: avatars[2],
        clientId: 'user1',
        clientName: 'Alex Morgan',
        packageId: 'p1',
        packageTitle: 'Power Session',
        datetime: '2026-01-05T14:00:00',
        status: 'completed',
        amount: 75,
        platformFee: 7.5,
        payoutAmount: 67.5,
    },
    {
        id: 'b5',
        coachId: '4',
        coachName: 'James Rodriguez',
        coachAvatar: avatars[3],
        clientId: 'user1',
        clientName: 'Alex Morgan',
        packageId: 'p10',
        packageTitle: 'WOD Session',
        datetime: '2026-01-03T07:00:00',
        status: 'cancelled',
        amount: 70,
        platformFee: 7,
        payoutAmount: 63,
    },
];

export const conversations: Conversation[] = [
    {
        id: 'conv1',
        participantId: '1',
        participantName: 'Sarah Mitchell',
        participantAvatar: avatars[2],
        lastMessage: 'Perfect! See you at 9am tomorrow.',
        lastMessageTime: '2026-01-15T14:32:00',
        unreadCount: 0,
    },
    {
        id: 'conv2',
        participantId: '3',
        participantName: 'Emma Chen',
        participantAvatar: avatars[0],
        lastMessage: 'I have a new yoga flow I think you\'ll love!',
        lastMessageTime: '2026-01-15T10:15:00',
        unreadCount: 2,
    },
    {
        id: 'conv3',
        participantId: '2',
        participantName: 'Marcus Johnson',
        participantAvatar: avatars[1],
        lastMessage: 'Great progress on your lifts! Keep it up.',
        lastMessageTime: '2026-01-14T18:45:00',
        unreadCount: 0,
    },
    {
        id: 'conv4',
        participantId: '4',
        participantName: 'James Rodriguez',
        participantAvatar: avatars[3],
        lastMessage: 'Would you like to reschedule for next week?',
        lastMessageTime: '2026-01-13T09:20:00',
        unreadCount: 1,
    },
];

export const messages: Record<string, Message[]> = {
    conv1: [
        { id: 'm1', threadId: 'conv1', senderId: 'user1', content: 'Hi Sarah! I wanted to confirm our session tomorrow.', timestamp: '2026-01-15T14:00:00', status: 'read', type: 'text' },
        { id: 'm2', threadId: 'conv1', senderId: '1', content: 'Hey Alex! Yes, we\'re all set for 9am at the downtown gym.', timestamp: '2026-01-15T14:15:00', status: 'read', type: 'text' },
        { id: 'm3', threadId: 'conv1', senderId: 'user1', content: 'Should I bring anything specific?', timestamp: '2026-01-15T14:20:00', status: 'read', type: 'text' },
        { id: 'm4', threadId: 'conv1', senderId: '1', content: 'Just water and comfortable workout clothes. We\'ll be focusing on compound lifts today.', timestamp: '2026-01-15T14:28:00', status: 'read', type: 'text' },
        { id: 'm5', threadId: 'conv1', senderId: 'user1', content: 'Great, thank you!', timestamp: '2026-01-15T14:30:00', status: 'read', type: 'text' },
        { id: 'm6', threadId: 'conv1', senderId: '1', content: 'Perfect! See you at 9am tomorrow.', timestamp: '2026-01-15T14:32:00', status: 'read', type: 'text' },
    ],
    conv2: [
        { id: 'm7', threadId: 'conv2', senderId: '3', content: 'Good morning! How did you feel after our last session?', timestamp: '2026-01-15T09:00:00', status: 'read', type: 'text' },
        { id: 'm8', threadId: 'conv2', senderId: 'user1', content: 'So much better! My back pain is almost gone.', timestamp: '2026-01-15T09:30:00', status: 'read', type: 'text' },
        { id: 'm9', threadId: 'conv2', senderId: '3', content: 'That\'s wonderful to hear! The stretches are really helping.', timestamp: '2026-01-15T10:00:00', status: 'read', type: 'text' },
        { id: 'm10', threadId: 'conv2', senderId: '3', content: 'I have a new yoga flow I think you\'ll love!', timestamp: '2026-01-15T10:15:00', status: 'delivered', type: 'text' },
    ],
    conv3: [
        { id: 'm11', threadId: 'conv3', senderId: '2', content: 'Your deadlift form looked solid today!', timestamp: '2026-01-14T18:30:00', status: 'read', type: 'text' },
        { id: 'm12', threadId: 'conv3', senderId: 'user1', content: 'Thanks! Those cues you gave really helped.', timestamp: '2026-01-14T18:40:00', status: 'read', type: 'text' },
        { id: 'm13', threadId: 'conv3', senderId: '2', content: 'Great progress on your lifts! Keep it up.', timestamp: '2026-01-14T18:45:00', status: 'read', type: 'text' },
    ],
    conv4: [
        { id: 'm14', threadId: 'conv4', senderId: 'user1', content: 'Hey James, I need to cancel tomorrow\'s session unfortunately.', timestamp: '2026-01-13T09:00:00', status: 'read', type: 'text' },
        { id: 'm15', threadId: 'conv4', senderId: '4', content: 'No problem at all! Things happen.', timestamp: '2026-01-13T09:10:00', status: 'read', type: 'text' },
        { id: 'm16', threadId: 'conv4', senderId: '4', content: 'Would you like to reschedule for next week?', timestamp: '2026-01-13T09:20:00', status: 'delivered', type: 'text' },
    ],
};

export const reviews: Review[] = [
    {
        id: 'r1',
        coachId: '1',
        clientName: 'Michael S.',
        clientAvatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face',
        rating: 5,
        comment: 'Sarah is an incredible trainer! She pushed me to achieve goals I never thought possible. Her knowledge of strength training is top-notch.',
        date: '2026-01-10',
    },
    {
        id: 'r2',
        coachId: '1',
        clientName: 'Jennifer L.',
        clientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
        rating: 5,
        comment: 'Best trainer I\'ve ever worked with. Professional, knowledgeable, and truly cares about her clients\' success.',
        date: '2026-01-05',
    },
    {
        id: 'r3',
        coachId: '1',
        clientName: 'Robert K.',
        clientAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
        rating: 4,
        comment: 'Great sessions with Sarah. Very motivating and always brings new exercises to keep things interesting.',
        date: '2025-12-28',
    },
    {
        id: 'r4',
        coachId: '1',
        clientName: 'Amanda T.',
        clientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face',
        rating: 5,
        comment: 'I lost 20 pounds in 3 months working with Sarah. Her combination of training and nutrition advice is unbeatable.',
        date: '2025-12-15',
    },
    {
        id: 'r5',
        coachId: '3',
        clientName: 'Lisa M.',
        clientAvatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face',
        rating: 5,
        comment: 'Emma\'s yoga sessions have transformed my flexibility and mental clarity. Highly recommend!',
        date: '2026-01-12',
    },
    {
        id: 'r6',
        coachId: '3',
        clientName: 'David W.',
        clientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
        rating: 5,
        comment: 'Never thought I\'d enjoy yoga until I met Emma. She makes every session enjoyable and challenging.',
        date: '2026-01-08',
    },
];

export const specialties = [
    'Strength Training',
    'Weight Loss',
    'Bodybuilding',
    'Yoga',
    'Pilates',
    'CrossFit',
    'HIIT',
    'Nutrition',
    'Athletic Performance',
    'Rehabilitation',
    'Flexibility',
    'Endurance',
    'Kettlebell Training',
    'Running',
    'Functional Fitness',
    'Mindfulness',
];

export const locations = [
    'New York, NY',
    'Los Angeles, CA',
    'San Francisco, CA',
    'Miami, FL',
    'Chicago, IL',
    'Boston, MA',
    'Seattle, WA',
    'Austin, TX',
    'Denver, CO',
    'Atlanta, GA',
];
